---
apiVersion: v1
kind: Service
metadata:
  name: transactionprocessing-service
spec:
  selector:
    app: transactionprocessing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer